### ISSUE TITLE
Send command output while it is running rather than after

### ISSUE THREAD

**Issue by ctessum** [ctessum/gobra#11]
I think this can be done by changing [this line](https://github.com/ctessum/gobra/blob/master/gobra.go#L208) to `s.Root.SetOutput(w)`.

**Comment by khoin** [comment]
This might be more complicated than that. The client-side is currently programmed to only do stuff after the HTTP response is complete. Piping the output directly to the HTTPReponse writer on the Go side solves half of the problem. 

I will look into it next week. It _might_ be possible to have the client-side process the response even when it's not finished.

**Comment by khoin** [comment]
Putting this here for later reference: https://jakearchibald.com/2015/thats-so-fetch/

**Comment by khoin** [comment]
Also, considering websocket: https://github.com/gorilla/websocket
