### ISSUE TITLE
Freeze the "Execute" button and input fields while a command is running

### ISSUE THREAD

**Issue by ctessum** [ctessum/gobra#12]
Some commands take a long time to run. If a user tries to start a second command while the first one was running it would probably cause problems. Can we make the input fields and button non-interactive and greyed-out while a command is running? Bonus points if we can also make it so the fields were also non-interactive if the user opened a second browser window at the same address.

**Comment by khoin** [comment]
This should be easy. Right now, I can see that you're planning to use gobra only locally, so I will only resolve this on the client-side.

**Comment by ctessum** [comment]
Sounds good
