### ISSUE TITLE
Add ability to directly serve index.html without writing an intermediate file to disk

### ISSUE THREAD

**Issue by ctessum** [ctessum/gobra#13]
While there are probably some cases where it is desirable to write a static index.html file to disk and serve it from there, I think we will more frequently want to serve it directly from the server without an intermediate file. The following code from [this tutorial](https://golang.org/doc/articles/wiki/) gives an example of how to do that:

``` go
func editHandler(w http.ResponseWriter, r *http.Request) {
    title := r.URL.Path[len("/edit/"):]
    p, err := loadPage(title)
    if err != nil {
        p = &Page{Title: title}
    }
    t, _ := template.ParseFiles("edit.html")
    t.Execute(w, p)
}
```

What it is doing is writing the filled template directly back to the web client rather than saving it to disk and then reading it from disk to send to the client.

**Comment by khoin** [comment]
Fixed in https://github.com/ctessum/gobra/pull/15
