### ISSUE TITLE
Allow user to upload files

### ISSUE THREAD

**Issue by ctessum** [ctessum/gobra#21]
Currently, gobra handles input files by letting the user specify the path to the file, just like it handles any other string argument.

We would like for file inputs to be handled as a special case, where the user can optionally upload the file using the browser file dialog box, and then the server would receive the file, save it in an accessible location (e.g., a temporary directory), and then set the value for the argument in question to the location of the saved file.

Since `pflag` doesn't have any way of indicating that a flag should be a file, we could add a field to the `Server` called "FileFlags" or something like that that would specify which flags should be treated as files.

**Comment by khoin** [comment]
Resolved by #22
